language: cpp
sudo: required

matrix:
  include:

    # linux g++
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER='g++-7'
      script:
        - sudo locale-gen "en_US" "ru_RU"
        - make CXX=$COMPILER 

    # linux clang++
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: 
            - llvm-toolchain-precise-6.0
            - ubuntu-toolchain-r-test
          packages: 
            - clang-6.0
            - g++-7
      env: COMPILER='clang++-6.0'
      script:
        - sudo locale-gen "en_US" "ru_RU"
        - make CXX=$COMPILER 

    # mac clang++
    - os: osx
      osx_image: xcode12
      compiler: clang
      env: COMPILER='clang++'
      script:
        - make CXX=$COMPILER 

